### ISSUE TITLE
Remove automatic importing of STY in each UMLS source exported

### ISSUE THREAD

**Issue by jonquet** [sifrproject/umls2rdf#1]
@vemonet I think you did that last year but for some reason (maybe you did not push the code here) when @twktheainur used the software to export the new version of MSHFRE, we endup with STY being still included.

Any ideas?

**Comment by vemonet** [comment]
https://github.com/sifrproject/umls2rdf/commit/3165c9c3185c240ac9dd88e9f4286014e5c468eb

Effectivement je l'ai fait, mais pas dans la branche Master, je m'en occupe

**Comment by vemonet** [comment]
Mergé avec Master
