### ISSUE TITLE
Language tags use the UMLS three character language codes

### ISSUE THREAD

**Issue by twktheainur** [sifrproject/umls2rdf#3]
In RDF language tags for string literals are defined by https://tools.ietf.org/html/bcp47 stating that when two-letter codes are available for a given language is should be used instead of the three letter language code. 

Yet, umls2rdf always uses the UMLS three letter codes when extracting ontologies from UMLS. 

For example if one extracts MSHFRE, the French version of Mesh, all prefLabels and altLabels are tagged with the `@fre` language code, which instead should be `@fr`

**Comment by vemonet** [comment]
Langs are extracted from UMLS at this place:
https://github.com/sifrproject/umls2rdf/blob/master/umls2rdf.py#L484

Careful with some hardcoded lang:
https://github.com/sifrproject/umls2rdf/blob/master/umls2rdf.py#L135
https://github.com/sifrproject/umls2rdf/blob/master/umls2rdf.py#L310

**Comment by twktheainur** [comment]
@jonquet @vemonet fixed in 809d5f3

I added a dictionary containing the three letter to two letter language code mapping for all language codes appearing in UMLS as of the last version (LAT field).

**Comment by jonquet** [comment]
Great! CC @alexskr and @mdorf For this.

@vemonet is supposed to do a pull request in case NCBO wants to fix this and a couple of others small changes e.g., #2
